# Form implementation generated from reading ui file 'c:\Users\juan2\OneDrive\Escritorio\University\ProyectoBases\ProyectoBD\ProyectoDB\views\LogIn.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_formLogIn(object):
    def setupUi(self, formLogIn):
        formLogIn.setObjectName("formLogIn")
        formLogIn.resize(482, 318)
        formLogIn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2 = QtWidgets.QLabel(parent=formLogIn)
        self.label_2.setGeometry(QtCore.QRect(140, 90, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=formLogIn)
        self.label_3.setGeometry(QtCore.QRect(100, 140, 91, 20))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=formLogIn)
        self.label_4.setGeometry(QtCore.QRect(100, 190, 91, 20))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.txtUsuario = QtWidgets.QLineEdit(parent=formLogIn)
        self.txtUsuario.setGeometry(QtCore.QRect(210, 140, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtUsuario.setFont(font)
        self.txtUsuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(0,0,0);\n"
"border-radius: 4px\n"
"")
        self.txtUsuario.setText("")
        self.txtUsuario.setMaxLength(32728)
        self.txtUsuario.setCursorPosition(0)
        self.txtUsuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtUsuario.setDragEnabled(False)
        self.txtUsuario.setReadOnly(False)
        self.txtUsuario.setPlaceholderText("Ingrese usuario")
        self.txtUsuario.setObjectName("txtUsuario")
        self.txtPassword = QtWidgets.QLineEdit(parent=formLogIn)
        self.txtPassword.setGeometry(QtCore.QRect(210, 180, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtPassword.setFont(font)
        self.txtPassword.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(0,0,0);\n"
"border-radius: 4px\n"
"")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtPassword.setObjectName("txtPassword")
        self.btnAcceder = QtWidgets.QPushButton(parent=formLogIn)
        self.btnAcceder.setGeometry(QtCore.QRect(210, 240, 82, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.btnAcceder.setFont(font)
        self.btnAcceder.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAcceder.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.btnAcceder.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(37, 99, 175);\n"
"border: 2px solid rgb(0,0,0);\n"
"border-radius:8px\n"
"")
        self.btnAcceder.setObjectName("btnAcceder")
        self.frame = QtWidgets.QFrame(parent=formLogIn)
        self.frame.setGeometry(QtCore.QRect(0, 0, 491, 61))
        self.frame.setStyleSheet("background-color: rgb(37, 99, 175);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(140, 0, 231, 51))
        self.label.setStyleSheet("background-color: rgb(37, 99, 175);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lblMensajeError = QtWidgets.QLabel(parent=formLogIn)
        self.lblMensajeError.setGeometry(QtCore.QRect(63, 290, 391, 20))
        self.lblMensajeError.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblMensajeError.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMensajeError.setObjectName("lblMensajeError")
        self.frame.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.txtUsuario.raise_()
        self.txtPassword.raise_()
        self.btnAcceder.raise_()
        self.lblMensajeError.raise_()

        self.retranslateUi(formLogIn)
        QtCore.QMetaObject.connectSlotsByName(formLogIn)

    def retranslateUi(self, formLogIn):
        _translate = QtCore.QCoreApplication.translate
        formLogIn.setWindowTitle(_translate("formLogIn", "Inicio de sesión"))
        self.label_2.setText(_translate("formLogIn", "Inicio de sesión"))
        self.label_3.setText(_translate("formLogIn", "Usuario"))
        self.label_4.setText(_translate("formLogIn", "Contraseña"))
        self.txtPassword.setPlaceholderText(_translate("formLogIn", "Ingrese contraseña"))
        self.btnAcceder.setText(_translate("formLogIn", "Acceder"))
        self.label.setText(_translate("formLogIn", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">Banco UQ</span></p></body></html>"))
        self.lblMensajeError.setText(_translate("formLogIn", "Mensaje"))
