# Form implementation generated from reading ui file 'c:\Users\juan2\OneDrive\Escritorio\University\ProyectoBases\ProyectoBD\ProyectoDB\views\Menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_menuWindow(object):
    def setupUi(self, menuWindow):
        menuWindow.setObjectName("menuWindow")
        menuWindow.resize(559, 317)
        font = QtGui.QFont()
        font.setPointSize(10)
        menuWindow.setFont(font)
        menuWindow.setAutoFillBackground(False)
        menuWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        menuWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(parent=menuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLogOut = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogOut.setGeometry(QtCore.QRect(450, 270, 93, 28))
        self.btnLogOut.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLogOut.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.btnLogOut.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(37, 99, 175);\n"
"border: 2px solid rgb(0, 0, 0);  \n"
"border-radius: 8px;  ")
        self.btnLogOut.setObjectName("btnLogOut")
        self.btnEntidades = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEntidades.setGeometry(QtCore.QRect(40, 140, 101, 41))
        self.btnEntidades.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnEntidades.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.btnEntidades.setAutoFillBackground(False)
        self.btnEntidades.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(202, 253, 255);\n"
"border: 2px solid rgb(0, 0, 0);  \n"
"border-radius: 8px;  ")
        self.btnEntidades.setObjectName("btnEntidades")
        self.btnSucursales = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSucursales.setGeometry(QtCore.QRect(40, 200, 101, 41))
        self.btnSucursales.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSucursales.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.btnSucursales.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(202, 253, 255);\n"
"border: 2px solid rgb(0, 0, 0);  \n"
"border-radius: 8px;  ")
        self.btnSucursales.setObjectName("btnSucursales")
        self.lblEntidades = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblEntidades.setEnabled(False)
        self.lblEntidades.setGeometry(QtCore.QRect(50, 80, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblEntidades.setFont(font)
        self.lblEntidades.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.lblEntidades.setObjectName("lblEntidades")
        self.btnCuotas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCuotas.setGeometry(QtCore.QRect(220, 200, 101, 41))
        self.btnCuotas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCuotas.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.btnCuotas.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(202, 253, 255);\n"
"border: 2px solid rgb(0, 0, 0);  \n"
"border-radius: 8px;  ")
        self.btnCuotas.setObjectName("btnCuotas")
        self.btnPrestamos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPrestamos.setGeometry(QtCore.QRect(220, 140, 101, 41))
        self.btnPrestamos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPrestamos.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.btnPrestamos.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.btnPrestamos.setAutoFillBackground(False)
        self.btnPrestamos.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(202, 253, 255);\n"
"border: 2px solid rgb(0, 0, 0);  \n"
"border-radius: 8px;  ")
        self.btnPrestamos.setObjectName("btnPrestamos")
        self.lblTransacciones = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTransacciones.setEnabled(False)
        self.lblTransacciones.setGeometry(QtCore.QRect(210, 80, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblTransacciones.setFont(font)
        self.lblTransacciones.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.lblTransacciones.setObjectName("lblTransacciones")
        self.btnConsultas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConsultas.setGeometry(QtCore.QRect(390, 200, 101, 41))
        self.btnConsultas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnConsultas.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.btnConsultas.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(202, 253, 255);\n"
"border: 2px solid rgb(0, 0, 0);  \n"
"border-radius: 8px;  ")
        self.btnConsultas.setObjectName("btnConsultas")
        self.btnReportes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnReportes.setGeometry(QtCore.QRect(390, 140, 101, 41))
        self.btnReportes.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnReportes.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.btnReportes.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.btnReportes.setAutoFillBackground(False)
        self.btnReportes.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(202, 253, 255);\n"
"border: 2px solid rgb(0, 0, 0);  \n"
"border-radius: 8px;  ")
        self.btnReportes.setObjectName("btnReportes")
        self.lblInformacion = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblInformacion.setEnabled(False)
        self.lblInformacion.setGeometry(QtCore.QRect(390, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblInformacion.setFont(font)
        self.lblInformacion.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.lblInformacion.setWordWrap(True)
        self.lblInformacion.setObjectName("lblInformacion")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 561, 51))
        self.frame.setStyleSheet("background-color: rgb(37, 99, 175);\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(3)
        self.frame.setMidLineWidth(3)
        self.frame.setObjectName("frame")
        self.lblMenu = QtWidgets.QLabel(parent=self.frame)
        self.lblMenu.setEnabled(False)
        self.lblMenu.setGeometry(QtCore.QRect(240, 10, 81, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.lblMenu.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblMenu.setFont(font)
        self.lblMenu.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.lblMenu.setAutoFillBackground(False)
        self.lblMenu.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lblMenu.setObjectName("lblMenu")
        menuWindow.setCentralWidget(self.centralwidget)
        self.actionEmpleados = QtGui.QAction(parent=menuWindow)
        self.actionEmpleados.setObjectName("actionEmpleados")
        self.actionTesoreria = QtGui.QAction(parent=menuWindow)
        self.actionTesoreria.setObjectName("actionTesoreria")
        self.actionEntidadessEmpleado = QtGui.QAction(parent=menuWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.actionEntidadessEmpleado.setFont(font)
        self.actionEntidadessEmpleado.setObjectName("actionEntidadessEmpleado")
        self.actionEntidadeSucursales = QtGui.QAction(parent=menuWindow)
        self.actionEntidadeSucursales.setObjectName("actionEntidadeSucursales")

        self.retranslateUi(menuWindow)
        QtCore.QMetaObject.connectSlotsByName(menuWindow)

    def retranslateUi(self, menuWindow):
        _translate = QtCore.QCoreApplication.translate
        menuWindow.setWindowTitle(_translate("menuWindow", "Menu"))
        self.btnLogOut.setText(_translate("menuWindow", "Cerrar sesión"))
        self.btnEntidades.setText(_translate("menuWindow", "Empleados"))
        self.btnSucursales.setText(_translate("menuWindow", "Sucursales"))
        self.lblEntidades.setText(_translate("menuWindow", "Entidades"))
        self.btnCuotas.setText(_translate("menuWindow", "Gestion de\n"
"Cuotas"))
        self.btnPrestamos.setText(_translate("menuWindow", "Solicitar \n"
"Prestamos"))
        self.lblTransacciones.setText(_translate("menuWindow", "Transacciones"))
        self.btnConsultas.setText(_translate("menuWindow", "Consultas"))
        self.btnReportes.setText(_translate("menuWindow", "Resportes"))
        self.lblInformacion.setText(_translate("menuWindow", "Informacion"))
        self.lblMenu.setText(_translate("menuWindow", "MENU"))
        self.actionEmpleados.setText(_translate("menuWindow", "Empleados"))
        self.actionTesoreria.setText(_translate("menuWindow", "Sucursales"))
        self.actionEntidadessEmpleado.setText(_translate("menuWindow", "Empleados"))
        self.actionEntidadeSucursales.setText(_translate("menuWindow", "Sucursales"))
